# CodeRabbit Configuration
# Configuración para habilitar revisiones automáticas en ramas dev y main

reviews:
  # Habilitar revisiones en múltiples ramas base
  base_branches:
    - main
    - dev
  # Mostrar estado de revisión
  review_status: true

# Configuración de paths a revisar (opcional)
paths:
  # Incluir todos los archivos Python
  - "**/*.py"
  # Incluir archivos de configuración
  - "**/*.yaml"
  - "**/*.yml"
  - "**/*.json"

