# Generated by Django 5.2.7 on 2025-10-13 14:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('heygen_avatar', 'HeyGen Avatar'), ('gemini_veo', 'Gemini Veo')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('script', models.TextField(help_text='Guión del video')),
                ('config', models.JSONField(default=dict, help_text='Configuración específica (avatar_id, voice_id, background, etc.)')),
                ('gcs_path', models.CharField(blank=True, help_text='Ruta del video en Google Cloud Storage', max_length=500, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duración en segundos', null=True)),
                ('resolution', models.CharField(blank=True, help_text='Resolución del video (ej: 1280x720)', max_length=20, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Metadata adicional de la API')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, help_text='ID del video en la plataforma externa (HeyGen, Gemini)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.project')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
