# Generated by Django 5.2.7 on 2025-12-02 09:24

import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


# =============================================================================
# Funciones copiadas de las migraciones originales
# =============================================================================

def migrate_heygen_to_v2(apps, schema_editor):
    """Migra los servicios 'heygen' existentes a 'heygen_v2'"""
    Scene = apps.get_model('core', 'Scene')
    Scene.objects.filter(ai_service='heygen').update(ai_service='heygen_v2')


def reverse_heygen_migration(apps, schema_editor):
    """Revierte la migración de heygen_v2 a heygen"""
    Scene = apps.get_model('core', 'Scene')
    Scene.objects.filter(ai_service='heygen_v2').update(ai_service='heygen')
    Scene.objects.filter(ai_service='heygen_avatar_iv').update(ai_service='heygen')


def assign_project_owners(apps, schema_editor):
    """Asigna un owner a todos los proyectos existentes que no tengan uno."""
    Project = apps.get_model('core', 'Project')
    User = apps.get_model('auth', 'User')
    
    projects_without_owner = Project.objects.filter(owner__isnull=True)
    
    if projects_without_owner.exists():
        first_user = User.objects.filter(is_active=True).order_by('id').first()
        
        if first_user:
            projects_without_owner.update(owner=first_user)


def reverse_assign_project_owners(apps, schema_editor):
    """Reversa la migración (no hace nada)"""
    pass


def create_groups_and_permissions(apps, schema_editor):
    """Crea los grupos de permisos y asigna los permisos correspondientes con IDs específicos"""
    
    db = schema_editor.connection
    is_postgres = 'postgresql' in db.vendor
    
    groups_data = [
        (3, 'usar'),
        (4, 'ver'),
        (5, 'crear'),
        (6, 'editar'),
        (7, 'borrar'),
        (8, 'admin'),
    ]
    
    group_permissions_data = [
        # Grupo 4 (ver): IDs 41-60
        (41, 4, 4), (42, 4, 8), (43, 4, 12), (44, 4, 16), (45, 4, 20),
        (46, 4, 24), (47, 4, 28), (48, 4, 32), (49, 4, 36), (50, 4, 40),
        (51, 4, 44), (52, 4, 48), (53, 4, 52), (54, 4, 56), (55, 4, 60),
        (56, 4, 64), (57, 4, 68), (58, 4, 72), (59, 4, 76), (60, 4, 80),
        # Grupo 3 (usar): IDs 61-80
        (61, 3, 61), (62, 3, 62), (63, 3, 63), (64, 3, 64), (65, 3, 65),
        (66, 3, 66), (67, 3, 67), (68, 3, 68), (69, 3, 69), (70, 3, 70),
        (71, 3, 71), (72, 3, 72), (73, 3, 73), (74, 3, 74), (75, 3, 75),
        (76, 3, 76), (77, 3, 77), (78, 3, 78), (79, 3, 79), (80, 3, 80),
        # Grupo 6 (editar): IDs 81-100
        (81, 6, 2), (82, 6, 6), (83, 6, 10), (84, 6, 14), (85, 6, 18),
        (86, 6, 22), (87, 6, 26), (88, 6, 30), (89, 6, 34), (90, 6, 38),
        (91, 6, 42), (92, 6, 46), (93, 6, 50), (94, 6, 54), (95, 6, 58),
        (96, 6, 62), (97, 6, 66), (98, 6, 70), (99, 6, 74), (100, 6, 78),
        # Grupo 5 (crear): IDs 101-120
        (101, 5, 1), (102, 5, 5), (103, 5, 9), (104, 5, 13), (105, 5, 17),
        (106, 5, 21), (107, 5, 25), (108, 5, 29), (109, 5, 33), (110, 5, 37),
        (111, 5, 41), (112, 5, 45), (113, 5, 49), (114, 5, 53), (115, 5, 57),
        (116, 5, 61), (117, 5, 65), (118, 5, 69), (119, 5, 73), (120, 5, 77),
        # Grupo 7 (borrar): IDs 121-140
        (121, 7, 3), (122, 7, 7), (123, 7, 11), (124, 7, 15), (125, 7, 19),
        (126, 7, 23), (127, 7, 27), (128, 7, 31), (129, 7, 35), (130, 7, 39),
        (131, 7, 43), (132, 7, 47), (133, 7, 51), (134, 7, 55), (135, 7, 59),
        (136, 7, 63), (137, 7, 67), (138, 7, 71), (139, 7, 75), (140, 7, 79),
        # Grupo 8 (admin): IDs 141-220 (permisos 1-80)
        (141, 8, 1), (142, 8, 2), (143, 8, 3), (144, 8, 4), (145, 8, 5),
        (146, 8, 6), (147, 8, 7), (148, 8, 8), (149, 8, 9), (150, 8, 10),
        (151, 8, 11), (152, 8, 12), (153, 8, 13), (154, 8, 14), (155, 8, 15),
        (156, 8, 16), (157, 8, 17), (158, 8, 18), (159, 8, 19), (160, 8, 20),
        (161, 8, 21), (162, 8, 22), (163, 8, 23), (164, 8, 24), (165, 8, 25),
        (166, 8, 26), (167, 8, 27), (168, 8, 28), (169, 8, 29), (170, 8, 30),
        (171, 8, 31), (172, 8, 32), (173, 8, 33), (174, 8, 34), (175, 8, 35),
        (176, 8, 36), (177, 8, 37), (178, 8, 38), (179, 8, 39), (180, 8, 40),
        (181, 8, 41), (182, 8, 42), (183, 8, 43), (184, 8, 44), (185, 8, 45),
        (186, 8, 46), (187, 8, 47), (188, 8, 48), (189, 8, 49), (190, 8, 50),
        (191, 8, 51), (192, 8, 52), (193, 8, 53), (194, 8, 54), (195, 8, 55),
        (196, 8, 56), (197, 8, 57), (198, 8, 58), (199, 8, 59), (200, 8, 60),
        (201, 8, 61), (202, 8, 62), (203, 8, 63), (204, 8, 64), (205, 8, 65),
        (206, 8, 66), (207, 8, 67), (208, 8, 68), (209, 8, 69), (210, 8, 70),
        (211, 8, 71), (212, 8, 72), (213, 8, 73), (214, 8, 74), (215, 8, 75),
        (216, 8, 76), (217, 8, 77), (218, 8, 78), (219, 8, 79), (220, 8, 80),
    ]
    
    raw_conn = schema_editor.connection.connection
    cursor = raw_conn.cursor()
    
    try:
        for group_id, group_name in groups_data:
            if is_postgres:
                cursor.execute(
                    "INSERT INTO auth_group (id, name) VALUES (%s, %s) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name",
                    (group_id, group_name)
                )
            else:
                cursor.execute(
                    "INSERT OR REPLACE INTO auth_group (id, name) VALUES (?, ?)",
                    (group_id, group_name)
                )
        
        for agp_id, group_id, permission_id in group_permissions_data:
            if is_postgres:
                cursor.execute("SELECT COUNT(*) FROM auth_group WHERE id = %s", (group_id,))
            else:
                cursor.execute("SELECT COUNT(*) FROM auth_group WHERE id = ?", (group_id,))
            group_exists = cursor.fetchone()[0] > 0
            
            if is_postgres:
                cursor.execute("SELECT COUNT(*) FROM auth_permission WHERE id = %s", (permission_id,))
            else:
                cursor.execute("SELECT COUNT(*) FROM auth_permission WHERE id = ?", (permission_id,))
            perm_exists = cursor.fetchone()[0] > 0
            
            if group_exists and perm_exists:
                if is_postgres:
                    cursor.execute(
                        "INSERT INTO auth_group_permissions (id, group_id, permission_id) VALUES (%s, %s, %s) ON CONFLICT (id) DO NOTHING",
                        (agp_id, group_id, permission_id)
                    )
                else:
                    cursor.execute(
                        "INSERT OR IGNORE INTO auth_group_permissions (id, group_id, permission_id) VALUES (?, ?, ?)",
                        (agp_id, group_id, permission_id)
                    )
        
        raw_conn.commit()
    finally:
        cursor.close()


def reverse_groups_permissions(apps, schema_editor):
    """Elimina los grupos y permisos creados"""
    raw_conn = schema_editor.connection.connection
    cursor = raw_conn.cursor()
    
    try:
        cursor.execute("DELETE FROM auth_group_permissions WHERE id BETWEEN 41 AND 220")
        cursor.execute("DELETE FROM auth_group WHERE id BETWEEN 3 AND 8")
        raw_conn.commit()
    finally:
        cursor.close()


def gen_uuid_video_image_audio(apps, schema_editor):
    """Generar UUIDs únicos para Video, Image, Audio existentes"""
    Video = apps.get_model('core', 'Video')
    Image = apps.get_model('core', 'Image')
    Audio = apps.get_model('core', 'Audio')
    
    for model in [Video, Image, Audio]:
        for obj in model.objects.all():
            obj.uuid = uuid.uuid4()
            obj.save(update_fields=['uuid'])


def gen_uuid_project(apps, schema_editor):
    """Generar UUIDs únicos para Project existentes"""
    Project = apps.get_model('core', 'Project')
    for project in Project.objects.all():
        project.uuid = uuid.uuid4()
        project.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_alter_video_type'), ('core', '0003_image'), ('core', '0004_alter_video_type'), ('core', '0005_script'), ('core', '0006_script_desired_duration_min'), ('core', '0007_script_agent_flow_script_final_video_scene'), ('core', '0008_script_video_config'), ('core', '0009_scene_image_source_freepik'), ('core', '0010_update_heygen_services'), ('core', '0011_scene_audio_duration_scene_audio_error_message_and_more'), ('core', '0012_scene_visual_prompt_alter_scene_script_text'), ('core', '0013_music'), ('core', '0014_add_project_sharing'), ('core', '0015_assign_project_owners'), ('core', '0016_alter_audio_project_alter_image_project_and_more'), ('core', '0017_audio_created_by_image_created_by_music_created_by_and_more'), ('core', '0018_usercredits_credittransaction_serviceusage'), ('core', '0019_add_permission_groups'), ('core', '0020_increase_video_type_max_length'), ('core', '0021_alter_scene_ai_service'), ('core', '0022_add_generation_task'), ('core', '0023_add_notification'), ('core', '0024_rename_core_genera_user_id_idx_generation__user_id_7f7fbf_idx_and_more'), ('core', '0025_fix_generation_task_task_id_nullable'), ('core', '0026_add_uuid_to_video_image_audio'), ('core', '0027_add_uuid_to_project'), ('core', '0028_unify_audio_music'), ('core', '0029_unify_audio_music'), ('core', '0030_remove_unique_from_task_id')]

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text_to_image', 'Texto a Imagen'), ('image_to_image', 'Imagen a Imagen (Edición)'), ('multi_image', 'Múltiples Imágenes (Composición)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('prompt', models.TextField(help_text='Prompt descriptivo para la imagen')),
                ('config', models.JSONField(default=dict, help_text='Configuración específica (aspect_ratio, response_modalities, etc.)')),
                ('gcs_path', models.CharField(blank=True, help_text='Ruta de la imagen en Google Cloud Storage', max_length=500, null=True)),
                ('width', models.IntegerField(blank=True, help_text='Ancho de la imagen en pixels', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Alto de la imagen en pixels', null=True)),
                ('aspect_ratio', models.CharField(blank=True, help_text='Relación de aspecto (ej: 16:9, 1:1)', max_length=10, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Metadata adicional de la API')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, help_text='ID de la generación en Gemini', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('heygen_avatar_v2', 'HeyGen Avatar V2'), ('heygen_avatar_iv', 'HeyGen Avatar IV'), ('gemini_veo', 'Gemini Veo'), ('sora', 'OpenAI Sora')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('script', models.TextField(help_text='Guión del video')),
                ('config', models.JSONField(default=dict, help_text='Configuración específica (avatar_id, voice_id, background, etc.)')),
                ('gcs_path', models.CharField(blank=True, help_text='Ruta del video en Google Cloud Storage', max_length=500, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duración en segundos', null=True)),
                ('resolution', models.CharField(blank=True, help_text='Resolución del video (ej: 1280x720)', max_length=20, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Metadata adicional de la API')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, help_text='ID del video en la plataforma externa (HeyGen, Gemini)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.project')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('original_script', models.TextField(help_text='Guión original enviado')),
                ('processed_data', models.JSONField(default=dict, help_text='Datos procesados por n8n (project, scenes, etc.)')),
                ('platform_mode', models.CharField(blank=True, help_text='Modo de plataforma (mixto, etc.)', max_length=50, null=True)),
                ('num_scenes', models.IntegerField(blank=True, help_text='Número de escenas', null=True)),
                ('language', models.CharField(blank=True, help_text='Idioma del guión', max_length=10, null=True)),
                ('total_estimated_duration_min', models.IntegerField(blank=True, help_text='Duración total estimada en minutos', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='core.project')),
                ('desired_duration_min', models.IntegerField(default=5, help_text='Duración deseada del video en minutos')),
                ('agent_flow', models.BooleanField(default=False, help_text='True si fue creado por el flujo del agente')),
                ('final_video', models.ForeignKey(blank=True, help_text='Video final combinado generado por el agente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_script', to='core.video')),
                ('video_type', models.CharField(blank=True, choices=[('ultra', 'Modo Ultra (Veo3 y Sora2)'), ('avatar', 'Con Avatares (HeyGen)'), ('general', 'Video General')], help_text='Tipo de video para el flujo del agente', max_length=20, null=True)),
                ('video_orientation', models.CharField(choices=[('16:9', 'Horizontal (16:9)'), ('9:16', 'Vertical (9:16)')], default='16:9', help_text='Orientación del video (heredada a todas las escenas)', max_length=10)),
                ('generate_previews', models.BooleanField(default=True, help_text='Si se deben generar previews automáticamente')),
            ],
            options={
                'verbose_name': 'Guión',
                'verbose_name_plural': 'Guiones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_id', models.CharField(help_text='ID de la escena (ej: "Escena 1")', max_length=50)),
                ('summary', models.TextField(help_text='Resumen breve del contenido de la escena')),
                ('script_text', models.TextField(help_text='Texto literal y completo del guión para esta escena')),
                ('duration_sec', models.IntegerField(help_text='Duración de la escena en segundos')),
                ('avatar', models.CharField(help_text='Indica si tiene avatar visible (si/no)', max_length=10)),
                ('platform', models.CharField(help_text='Plataforma sugerida por n8n (gemini_veo, sora, heygen)', max_length=50)),
                ('broll', models.JSONField(default=list, help_text='Lista de elementos visuales sugeridos para B-roll')),
                ('transition', models.CharField(blank=True, help_text='Tipo de transición (corte, fundido, deslizamiento, etc.)', max_length=100, null=True)),
                ('text_on_screen', models.TextField(blank=True, help_text='Texto para mostrar en pantalla', null=True)),
                ('audio_notes', models.TextField(blank=True, help_text='Notas sobre tono, música y efectos de audio', null=True)),
                ('order', models.IntegerField(help_text='Orden de la escena en la secuencia del video (0, 1, 2...)')),
                ('is_included', models.BooleanField(default=True, help_text='Si está marcada para incluir en el video final')),
                ('preview_image_gcs_path', models.CharField(blank=True, help_text='Ruta de la imagen preview en GCS', max_length=500, null=True)),
                ('preview_image_status', models.CharField(choices=[('pending', 'Pendiente'), ('generating', 'Generando'), ('completed', 'Completada'), ('error', 'Error')], default='pending', help_text='Estado de generación de la imagen preview', max_length=20)),
                ('preview_image_error', models.TextField(blank=True, help_text='Mensaje de error si falla la generación del preview', null=True)),
                ('ai_service', models.CharField(choices=[('gemini_veo', 'Gemini Veo'), ('sora', 'OpenAI Sora'), ('heygen', 'HeyGen Avatar')], help_text='Servicio de IA seleccionado para generar el video', max_length=50)),
                ('ai_config', models.JSONField(default=dict, help_text='Configuración específica del servicio (avatar_id, voice_id, duration, etc.)')),
                ('video_gcs_path', models.CharField(blank=True, help_text='Ruta del video generado en GCS', max_length=500, null=True)),
                ('video_status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', help_text='Estado de generación del video', max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='ID del video en la plataforma externa (HeyGen, Gemini, Sora)', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si falla la generación del video', null=True)),
                ('version', models.IntegerField(default=1, help_text='Versión de la escena (incrementa con cada regeneración)')),
                ('metadata', models.JSONField(default=dict, help_text='Metadata adicional de la API o del proceso')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('parent_scene', models.ForeignKey(blank=True, help_text='Escena padre si es una versión regenerada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='core.scene')),
                ('project', models.ForeignKey(help_text='Proyecto al que pertenece (para consultas directas)', on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='core.project')),
                ('script', models.ForeignKey(help_text='Guión del que forma parte esta escena', on_delete=django.db.models.deletion.CASCADE, related_name='db_scenes', to='core.script')),
                ('image_source', models.CharField(choices=[('ai_generated', 'Generada con IA'), ('freepik_stock', 'Freepik Stock'), ('user_upload', 'Subida por Usuario')], default='ai_generated', help_text='Origen de la imagen preview/referencia', max_length=20)),
                ('freepik_resource_id', models.CharField(blank=True, help_text='ID del recurso de Freepik si se usó stock', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Escena',
                'verbose_name_plural': 'Escenas',
                'ordering': ['order'],
                'unique_together': {('script', 'scene_id')},
            },
        ),
        migrations.RunPython(
            code=migrate_heygen_to_v2,
            reverse_code=reverse_heygen_migration,
        ),
        migrations.AddField(
            model_name='scene',
            name='audio_duration',
            field=models.FloatField(blank=True, help_text='Duración del audio en segundos', null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='audio_error_message',
            field=models.TextField(blank=True, help_text='Mensaje de error si falla la generación del audio', null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='audio_gcs_path',
            field=models.CharField(blank=True, help_text='Ruta del audio narrado en GCS (ElevenLabs TTS)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='audio_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', help_text='Estado de generación del audio', max_length=20),
        ),
        migrations.AddField(
            model_name='scene',
            name='audio_voice_id',
            field=models.CharField(blank=True, help_text='ID de la voz de ElevenLabs usada', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='audio_voice_name',
            field=models.CharField(blank=True, help_text='Nombre de la voz de ElevenLabs', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='final_video_gcs_path',
            field=models.CharField(blank=True, help_text='Ruta del video final con audio combinado en GCS', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='final_video_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', help_text='Estado de combinación del video final', max_length=20),
        ),
        migrations.AddField(
            model_name='script',
            name='default_voice_id',
            field=models.CharField(blank=True, help_text='ID de voz por defecto de ElevenLabs para todas las escenas', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='default_voice_name',
            field=models.CharField(blank=True, help_text='Nombre de voz por defecto de ElevenLabs', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='enable_audio',
            field=models.BooleanField(default=True, help_text='Si True, genera audio automáticamente para escenas Veo/Sora'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='ai_service',
            field=models.CharField(choices=[('gemini_veo', 'Gemini Veo'), ('sora', 'OpenAI Sora'), ('heygen_v2', 'HeyGen Avatar V2'), ('heygen_avatar_iv', 'HeyGen Avatar IV'), ('vuela_ai', 'Vuela.ai')], help_text='Servicio de IA seleccionado para generar el video', max_length=50),
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('text', models.TextField(help_text='Texto para convertir a voz')),
                ('voice_id', models.CharField(help_text='ID de la voz en ElevenLabs', max_length=100)),
                ('voice_name', models.CharField(blank=True, help_text='Nombre de la voz (para mostrar en UI)', max_length=100, null=True)),
                ('model_id', models.CharField(default='eleven_turbo_v2_5', help_text='Modelo de ElevenLabs (eleven_turbo_v2_5, eleven_multilingual_v2, etc.)', max_length=100)),
                ('language_code', models.CharField(default='es', help_text='Código de idioma (ISO 639-1)', max_length=10)),
                ('voice_settings', models.JSONField(default=dict, help_text='Configuración de voz: stability, similarity_boost, style, speed')),
                ('gcs_path', models.CharField(blank=True, help_text='Ruta del audio en Google Cloud Storage', max_length=500, null=True)),
                ('duration', models.FloatField(blank=True, help_text='Duración del audio en segundos', null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('format', models.CharField(default='mp3', help_text='Formato del audio (mp3, wav, etc.)', max_length=10)),
                ('sample_rate', models.IntegerField(blank=True, help_text='Sample rate del audio (44100, 48000, etc.)', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Metadata adicional de la API')),
                ('alignment', models.JSONField(blank=True, default=dict, help_text='Datos de sincronización carácter por carácter')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, help_text='ID de la generación en ElevenLabs (si aplica)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='core.project')),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='scene',
            name='visual_prompt',
            field=models.TextField(blank=True, help_text='Prompt visual para generar el video (Veo/Sora/Vuela) - en inglés', null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='script_text',
            field=models.TextField(help_text='Texto literal y completo del guión para narración (HeyGen + ElevenLabs)'),
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la pista musical', max_length=255)),
                ('prompt', models.TextField(help_text='Prompt usado para generar la música')),
                ('duration_ms', models.IntegerField(help_text='Duración de la música en milisegundos')),
                ('composition_plan', models.JSONField(blank=True, help_text='Plan de composición detallado (JSON) usado para generar la música', null=True)),
                ('song_metadata', models.JSONField(blank=True, help_text='Metadatos de la canción generada (tempo, key, mood, etc.)', null=True)),
                ('gcs_path', models.CharField(blank=True, help_text='Path en GCS donde está almacenada la música', max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('generating', 'Generando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('elevenlabs_track_id', models.CharField(blank=True, help_text='ID del track en ElevenLabs (si aplica)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se generó la música', null=True)),
                ('project', models.ForeignKey(help_text='Proyecto al que pertenece esta música', on_delete=django.db.models.deletion.CASCADE, related_name='music_tracks', to='core.project')),
            ],
            options={
                'verbose_name': 'Música',
                'verbose_name_plural': 'Músicas',
                'db_table': 'music',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Usuario propietario del proyecto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('editor', 'Editor')], default='editor', help_text='Rol del usuario en el proyecto', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el usuario se unió al proyecto')),
                ('project', models.ForeignKey(help_text='Proyecto al que pertenece el miembro', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.project')),
                ('user', models.ForeignKey(help_text='Usuario miembro del proyecto', on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de Proyecto',
                'verbose_name_plural': 'Miembros de Proyectos',
                'ordering': ['-joined_at'],
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Usuarios con acceso al proyecto', related_name='shared_projects', through='core.ProjectMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email del usuario invitado', max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('editor', 'Editor')], default='editor', help_text='Rol que se asignará al usuario cuando acepte', max_length=20)),
                ('token', models.CharField(help_text='Token único para aceptar la invitación', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='pending', help_text='Estado de la invitación', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la invitación')),
                ('expires_at', models.DateTimeField(help_text='Fecha de expiración de la invitación')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='Fecha en que se aceptó la invitación', null=True)),
                ('invited_by', models.ForeignKey(help_text='Usuario que envió la invitación', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Proyecto al que se invita', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.project')),
            ],
            options={
                'verbose_name': 'Invitación de Proyecto',
                'verbose_name_plural': 'Invitaciones de Proyectos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='core_projec_token_16853f_idx'), models.Index(fields=['email', 'status'], name='core_projec_email_e947ff_idx')],
            },
        ),
        migrations.RunPython(
            code=assign_project_owners,
            reverse_code=reverse_assign_project_owners,
        ),
        migrations.AlterField(
            model_name='audio',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='core.project'),
        ),
        migrations.AlterField(
            model_name='image',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project'),
        ),
        migrations.AlterField(
            model_name='music',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_tracks', to='core.project'),
        ),
        migrations.AlterField(
            model_name='script',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='core.project'),
        ),
        migrations.AlterField(
            model_name='video',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.project'),
        ),
        migrations.AddField(
            model_name='audio',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este audio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó esta imagen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='music',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó esta música', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='script',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este guión', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este video', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.DecimalField(decimal_places=2, default=0, help_text='Saldo actual de créditos', max_digits=10)),
                ('total_purchased', models.DecimalField(decimal_places=2, default=0, help_text='Total de créditos comprados históricamente', max_digits=10)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, help_text='Total de créditos gastados históricamente', max_digits=10)),
                ('monthly_limit', models.IntegerField(default=1000, help_text='Límite mensual de créditos')),
                ('current_month_usage', models.DecimalField(decimal_places=2, default=0, help_text='Créditos usados en el mes actual', max_digits=10)),
                ('last_reset_date', models.DateField(blank=True, help_text='Última fecha de reset mensual', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Créditos de Usuario',
                'verbose_name_plural': 'Créditos de Usuarios',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Compra'), ('spend', 'Gasto'), ('refund', 'Reembolso'), ('adjustment', 'Ajuste'), ('monthly_reset', 'Reset Mensual')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cantidad de créditos (positivo para compras, negativo para gastos)', max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Saldo antes de la transacción', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Saldo después de la transacción', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Descripción de la transacción')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('service_name', models.CharField(blank=True, help_text='Nombre del servicio usado (gemini_veo, sora, etc.)', max_length=50)),
                ('metadata', models.JSONField(default=dict, help_text='Información adicional (duración, tokens, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción de Créditos',
                'verbose_name_plural': 'Transacciones de Créditos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_credit_user_id_c97634_idx'), models.Index(fields=['user', 'transaction_type'], name='core_credit_user_id_a1d033_idx'), models.Index(fields=['service_name', '-created_at'], name='core_credit_service_034c55_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('gemini_veo', 'Gemini Veo'), ('sora', 'OpenAI Sora'), ('heygen_avatar_v2', 'HeyGen Avatar V2'), ('heygen_avatar_iv', 'HeyGen Avatar IV'), ('vuela_ai', 'Vuela.ai'), ('gemini_image', 'Gemini Image'), ('elevenlabs', 'ElevenLabs TTS'), ('elevenlabs_music', 'ElevenLabs Music')], max_length=50)),
                ('operation_type', models.CharField(choices=[('video_generation', 'Generación de Video'), ('image_generation', 'Generación de Imagen'), ('audio_generation', 'Generación de Audio'), ('music_generation', 'Generación de Música'), ('preview_generation', 'Generación de Preview')], max_length=50)),
                ('tokens_used', models.IntegerField(blank=True, help_text='Tokens consumidos (si aplica)', null=True)),
                ('credits_spent', models.DecimalField(decimal_places=2, help_text='Créditos gastados', max_digits=10)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=4, help_text='Costo real en USD', max_digits=10, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Info adicional (duración, resolución, caracteres, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso de Servicio',
                'verbose_name_plural': 'Usos de Servicios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_servic_user_id_664517_idx'), models.Index(fields=['user', 'service_name'], name='core_servic_user_id_cee68c_idx'), models.Index(fields=['service_name', '-created_at'], name='core_servic_service_5278a0_idx'), models.Index(fields=['created_at'], name='core_servic_created_ec7d32_idx')],
            },
        ),
        migrations.RunPython(
            code=create_groups_and_permissions,
            reverse_code=reverse_groups_permissions,
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('heygen_avatar_v2', 'HeyGen Avatar V2'), ('heygen_avatar_iv', 'HeyGen Avatar IV'), ('gemini_veo', 'Gemini Veo'), ('sora', 'OpenAI Sora'), ('higgsfield_dop_standard', 'Higgsfield DoP Standard'), ('higgsfield_dop_preview', 'Higgsfield DoP Preview'), ('higgsfield_seedance_v1_pro', 'Higgsfield Seedance V1 Pro'), ('higgsfield_kling_v2_1_pro', 'Higgsfield Kling V2.1 Pro'), ('kling_v1', 'Kling V1'), ('kling_v1_5', 'Kling V1.5'), ('kling_v1_6', 'Kling V1.6'), ('kling_v2_master', 'Kling V2 Master'), ('kling_v2_1', 'Kling V2.1'), ('kling_v2_5_turbo', 'Kling V2.5 Turbo')], max_length=30),
        ),
        migrations.AlterField(
            model_name='scene',
            name='ai_service',
            field=models.CharField(choices=[('gemini_veo', 'Gemini Veo'), ('sora', 'OpenAI Sora'), ('heygen_v2', 'HeyGen Avatar V2'), ('heygen_avatar_iv', 'HeyGen Avatar IV'), ('vuela_ai', 'Vuela.ai'), ('higgsfield_dop_standard', 'Higgsfield DoP Standard'), ('higgsfield_dop_preview', 'Higgsfield DoP Preview'), ('higgsfield_seedance_v1_pro', 'Higgsfield Seedance V1 Pro'), ('higgsfield_kling_v2_1_pro', 'Higgsfield Kling V2.1 Pro'), ('kling_v1', 'Kling V1'), ('kling_v1_5', 'Kling V1.5'), ('kling_v1_6', 'Kling V1.6'), ('kling_v2_master', 'Kling V2 Master'), ('kling_v2_1', 'Kling V2.1'), ('kling_v2_5_turbo', 'Kling V2.5 Turbo')], help_text='Servicio de IA seleccionado para generar el video', max_length=50),
        ),
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID único de la tarea', primary_key=True, serialize=False)),
                ('task_id', models.CharField(blank=True, db_index=True, help_text='Celery task ID (puede ser null antes de que Celery procese la tarea)', max_length=255, null=True)),
                ('task_type', models.CharField(choices=[('video', 'Video'), ('image', 'Imagen'), ('audio', 'Audio'), ('scene', 'Escena')], help_text='Tipo de generación', max_length=20)),
                ('item_uuid', models.UUIDField(db_index=True, help_text='UUID del item generado (no ID numérico)')),
                ('status', models.CharField(choices=[('queued', 'En Cola'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], db_index=True, default='queued', help_text='Estado de la tarea', max_length=20)),
                ('queue_name', models.CharField(help_text='Nombre de la cola de Celery', max_length=50)),
                ('priority', models.IntegerField(default=5, help_text='Prioridad (1-10, mayor = más prioridad, por tipo de generación)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error o razón de cancelación', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Número de reintentos realizados')),
                ('max_retries', models.IntegerField(default=3, help_text='Máximo número de reintentos permitidos')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata adicional (prompt, parámetros, etc.)')),
                ('user', models.ForeignKey(help_text='Usuario que creó la tarea', on_delete=django.db.models.deletion.CASCADE, related_name='generation_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea de Generación',
                'verbose_name_plural': 'Tareas de Generación',
                'db_table': 'generation_task',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='core_genera_user_id_idx'), models.Index(fields=['task_type', 'item_uuid'], name='core_genera_task_ty_idx'), models.Index(fields=['status', 'created_at'], name='core_genera_status_idx'), models.Index(fields=['queue_name', 'priority', 'created_at'], name='core_genera_queue_n_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID único de la notificación', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('generation_completed', 'Generación Completada'), ('generation_failed', 'Generación Fallida'), ('generation_progress', 'Progreso de Generación'), ('credits_low', 'Créditos Bajos'), ('credits_insufficient', 'Créditos Insuficientes'), ('project_invitation', 'Invitación de Proyecto'), ('system_maintenance', 'Mantenimiento del Sistema'), ('info', 'Información')], help_text='Tipo de notificación', max_length=50)),
                ('title', models.CharField(help_text='Título de la notificación', max_length=255)),
                ('message', models.TextField(help_text='Mensaje de la notificación')),
                ('read', models.BooleanField(db_index=True, default=False, help_text='Si la notificación ha sido leída')),
                ('action_url', models.CharField(blank=True, help_text='URL de acción (opcional)', max_length=500, null=True)),
                ('action_label', models.CharField(blank=True, help_text='Etiqueta del botón de acción', max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata adicional (progreso, item_uuid, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='Usuario destinatario', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read', 'created_at'], name='core_notifi_user_id_idx'), models.Index(fields=['user', 'type', 'created_at'], name='core_notifi_user_ty_idx')],
            },
        ),
        migrations.RenameIndex(
            model_name='generationtask',
            new_name='generation__user_id_7f7fbf_idx',
            old_name='core_genera_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='generationtask',
            new_name='generation__task_ty_5520e3_idx',
            old_name='core_genera_task_ty_idx',
        ),
        migrations.RenameIndex(
            model_name='generationtask',
            new_name='generation__status_9aa419_idx',
            old_name='core_genera_status_idx',
        ),
        migrations.RenameIndex(
            model_name='generationtask',
            new_name='generation__queue_n_5acd90_idx',
            old_name='core_genera_queue_n_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_92ac92_idx',
            old_name='core_notifi_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_6dfb7b_idx',
            old_name='core_notifi_user_ty_idx',
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('heygen_avatar_v2', 'HeyGen Avatar V2'), ('heygen_avatar_iv', 'HeyGen Avatar IV'), ('gemini_veo', 'Gemini Veo'), ('sora', 'OpenAI Sora'), ('higgsfield_dop_standard', 'Higgsfield DoP Standard'), ('higgsfield_dop_preview', 'Higgsfield DoP Preview'), ('higgsfield_seedance_v1_pro', 'Higgsfield Seedance V1 Pro'), ('higgsfield_kling_v2_1_pro', 'Higgsfield Kling V2.1 Pro'), ('kling_v1', 'Kling V1'), ('kling_v1_5', 'Kling V1.5'), ('kling_v1_6', 'Kling V1.6'), ('kling_v2_master', 'Kling V2 Master'), ('kling_v2_1', 'Kling V2.1'), ('kling_v2_5_turbo', 'Kling V2.5 Turbo'), ('manim_quote', 'Manim Quote')], max_length=30),
        ),
        migrations.AlterField(
            model_name='generationtask',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Celery task ID', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='video',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UUID público para URLs y storage', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UUID público para URLs y storage', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UUID público para URLs y storage', null=True),
        ),
        migrations.RunPython(
            code=gen_uuid_video_image_audio,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='video',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UUID público para URLs y storage', unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UUID público para URLs y storage', unique=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UUID público para URLs y storage', unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(
            code=gen_uuid_project,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='composition_plan',
            field=models.JSONField(blank=True, help_text='Plan de composición detallado (JSON)', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='duration_ms',
            field=models.IntegerField(blank=True, help_text='Duración de la música en milisegundos', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='elevenlabs_track_id',
            field=models.CharField(blank=True, help_text='ID del track en ElevenLabs Music', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='prompt',
            field=models.TextField(blank=True, help_text='Prompt usado para generar la música', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='song_metadata',
            field=models.JSONField(blank=True, help_text='Metadatos de la canción (tempo, key, mood, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='type',
            field=models.CharField(choices=[('tts', 'Text-to-Speech'), ('music', 'Música Generada')], db_index=True, default='tts', help_text='Tipo de audio: TTS o música generada', max_length=20),
        ),
        migrations.AlterField(
            model_name='audio',
            name='text',
            field=models.TextField(blank=True, help_text='Texto para convertir a voz (TTS)', null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='voice_id',
            field=models.CharField(blank=True, help_text='ID de la voz en ElevenLabs (TTS)', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.AlterField(
            model_name='generationtask',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Celery task ID (puede ser null antes de que Celery procese la tarea)', max_length=255, null=True),
        ),
    ]
