# Generated by Django 5.2.7 on 2025-10-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('heygen_avatar_v2', 'HeyGen Avatar V2'), ('heygen_avatar_iv', 'HeyGen Avatar IV'), ('gemini_veo', 'Gemini Veo')], max_length=20),
        ),
    ]
