# Generated by Django 5.2.7 on 2025-10-21 13:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_video_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text_to_image', 'Texto a Imagen'), ('image_to_image', 'Imagen a Imagen (Edición)'), ('multi_image', 'Múltiples Imágenes (Composición)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('prompt', models.TextField(help_text='Prompt descriptivo para la imagen')),
                ('config', models.JSONField(default=dict, help_text='Configuración específica (aspect_ratio, response_modalities, etc.)')),
                ('gcs_path', models.CharField(blank=True, help_text='Ruta de la imagen en Google Cloud Storage', max_length=500, null=True)),
                ('width', models.IntegerField(blank=True, help_text='Ancho de la imagen en pixels', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Alto de la imagen en pixels', null=True)),
                ('aspect_ratio', models.CharField(blank=True, help_text='Relación de aspecto (ej: 16:9, 1:1)', max_length=10, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Metadata adicional de la API')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, help_text='ID de la generación en Gemini', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'ordering': ['-created_at'],
            },
        ),
    ]
