# Generated by Django 5.2.7 on 2025-10-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('heygen_avatar_v2', 'HeyGen Avatar V2'), ('heygen_avatar_iv', 'HeyGen Avatar IV'), ('gemini_veo', 'Gemini Veo'), ('sora', 'OpenAI Sora')], max_length=20),
        ),
    ]
