# Generated by Django 5.2.7 on 2025-10-23 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_video_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('original_script', models.TextField(help_text='Guión original enviado')),
                ('processed_data', models.JSONField(default=dict, help_text='Datos procesados por n8n (project, scenes, etc.)')),
                ('platform_mode', models.CharField(blank=True, help_text='Modo de plataforma (mixto, etc.)', max_length=50, null=True)),
                ('num_scenes', models.IntegerField(blank=True, help_text='Número de escenas', null=True)),
                ('language', models.CharField(blank=True, help_text='Idioma del guión', max_length=10, null=True)),
                ('total_estimated_duration_min', models.IntegerField(blank=True, help_text='Duración total estimada en minutos', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='core.project')),
            ],
            options={
                'verbose_name': 'Guión',
                'verbose_name_plural': 'Guiones',
                'ordering': ['-created_at'],
            },
        ),
    ]
