# Generated by Django 5.2.7 on 2025-10-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='desired_duration_min',
            field=models.IntegerField(default=5, help_text='Duración deseada del video en minutos'),
        ),
    ]
