# Generated by Django 5.2.7 on 2025-10-28 10:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_script_desired_duration_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='agent_flow',
            field=models.BooleanField(default=False, help_text='True si fue creado por el flujo del agente'),
        ),
        migrations.AddField(
            model_name='script',
            name='final_video',
            field=models.ForeignKey(blank=True, help_text='Video final combinado generado por el agente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_script', to='core.video'),
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_id', models.CharField(help_text='ID de la escena (ej: "Escena 1")', max_length=50)),
                ('summary', models.TextField(help_text='Resumen breve del contenido de la escena')),
                ('script_text', models.TextField(help_text='Texto literal y completo del guión para esta escena')),
                ('duration_sec', models.IntegerField(help_text='Duración de la escena en segundos')),
                ('avatar', models.CharField(help_text='Indica si tiene avatar visible (si/no)', max_length=10)),
                ('platform', models.CharField(help_text='Plataforma sugerida por n8n (gemini_veo, sora, heygen)', max_length=50)),
                ('broll', models.JSONField(default=list, help_text='Lista de elementos visuales sugeridos para B-roll')),
                ('transition', models.CharField(blank=True, help_text='Tipo de transición (corte, fundido, deslizamiento, etc.)', max_length=100, null=True)),
                ('text_on_screen', models.TextField(blank=True, help_text='Texto para mostrar en pantalla', null=True)),
                ('audio_notes', models.TextField(blank=True, help_text='Notas sobre tono, música y efectos de audio', null=True)),
                ('order', models.IntegerField(help_text='Orden de la escena en la secuencia del video (0, 1, 2...)')),
                ('is_included', models.BooleanField(default=True, help_text='Si está marcada para incluir en el video final')),
                ('preview_image_gcs_path', models.CharField(blank=True, help_text='Ruta de la imagen preview en GCS', max_length=500, null=True)),
                ('preview_image_status', models.CharField(choices=[('pending', 'Pendiente'), ('generating', 'Generando'), ('completed', 'Completada'), ('error', 'Error')], default='pending', help_text='Estado de generación de la imagen preview', max_length=20)),
                ('preview_image_error', models.TextField(blank=True, help_text='Mensaje de error si falla la generación del preview', null=True)),
                ('ai_service', models.CharField(choices=[('gemini_veo', 'Gemini Veo'), ('sora', 'OpenAI Sora'), ('heygen', 'HeyGen Avatar')], help_text='Servicio de IA seleccionado para generar el video', max_length=50)),
                ('ai_config', models.JSONField(default=dict, help_text='Configuración específica del servicio (avatar_id, voice_id, duration, etc.)')),
                ('video_gcs_path', models.CharField(blank=True, help_text='Ruta del video generado en GCS', max_length=500, null=True)),
                ('video_status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', help_text='Estado de generación del video', max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='ID del video en la plataforma externa (HeyGen, Gemini, Sora)', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si falla la generación del video', null=True)),
                ('version', models.IntegerField(default=1, help_text='Versión de la escena (incrementa con cada regeneración)')),
                ('metadata', models.JSONField(default=dict, help_text='Metadata adicional de la API o del proceso')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('parent_scene', models.ForeignKey(blank=True, help_text='Escena padre si es una versión regenerada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='core.scene')),
                ('project', models.ForeignKey(help_text='Proyecto al que pertenece (para consultas directas)', on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='core.project')),
                ('script', models.ForeignKey(help_text='Guión del que forma parte esta escena', on_delete=django.db.models.deletion.CASCADE, related_name='db_scenes', to='core.script')),
            ],
            options={
                'verbose_name': 'Escena',
                'verbose_name_plural': 'Escenas',
                'ordering': ['order'],
                'unique_together': {('script', 'scene_id')},
            },
        ),
    ]
