# Generated by Django 5.1.6 on 2025-11-05 13:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_update_heygen_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='audio_duration',
            field=models.FloatField(blank=True, help_text='Duración del audio en segundos', null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='audio_error_message',
            field=models.TextField(blank=True, help_text='Mensaje de error si falla la generación del audio', null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='audio_gcs_path',
            field=models.CharField(blank=True, help_text='Ruta del audio narrado en GCS (ElevenLabs TTS)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='audio_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', help_text='Estado de generación del audio', max_length=20),
        ),
        migrations.AddField(
            model_name='scene',
            name='audio_voice_id',
            field=models.CharField(blank=True, help_text='ID de la voz de ElevenLabs usada', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='audio_voice_name',
            field=models.CharField(blank=True, help_text='Nombre de la voz de ElevenLabs', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='final_video_gcs_path',
            field=models.CharField(blank=True, help_text='Ruta del video final con audio combinado en GCS', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='final_video_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', help_text='Estado de combinación del video final', max_length=20),
        ),
        migrations.AddField(
            model_name='script',
            name='default_voice_id',
            field=models.CharField(blank=True, help_text='ID de voz por defecto de ElevenLabs para todas las escenas', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='default_voice_name',
            field=models.CharField(blank=True, help_text='Nombre de voz por defecto de ElevenLabs', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='enable_audio',
            field=models.BooleanField(default=True, help_text='Si True, genera audio automáticamente para escenas Veo/Sora'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='ai_service',
            field=models.CharField(choices=[('gemini_veo', 'Gemini Veo'), ('sora', 'OpenAI Sora'), ('heygen_v2', 'HeyGen Avatar V2'), ('heygen_avatar_iv', 'HeyGen Avatar IV'), ('vuela_ai', 'Vuela.ai')], help_text='Servicio de IA seleccionado para generar el video', max_length=50),
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('text', models.TextField(help_text='Texto para convertir a voz')),
                ('voice_id', models.CharField(help_text='ID de la voz en ElevenLabs', max_length=100)),
                ('voice_name', models.CharField(blank=True, help_text='Nombre de la voz (para mostrar en UI)', max_length=100, null=True)),
                ('model_id', models.CharField(default='eleven_turbo_v2_5', help_text='Modelo de ElevenLabs (eleven_turbo_v2_5, eleven_multilingual_v2, etc.)', max_length=100)),
                ('language_code', models.CharField(default='es', help_text='Código de idioma (ISO 639-1)', max_length=10)),
                ('voice_settings', models.JSONField(default=dict, help_text='Configuración de voz: stability, similarity_boost, style, speed')),
                ('gcs_path', models.CharField(blank=True, help_text='Ruta del audio en Google Cloud Storage', max_length=500, null=True)),
                ('duration', models.FloatField(blank=True, help_text='Duración del audio en segundos', null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('format', models.CharField(default='mp3', help_text='Formato del audio (mp3, wav, etc.)', max_length=10)),
                ('sample_rate', models.IntegerField(blank=True, help_text='Sample rate del audio (44100, 48000, etc.)', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Metadata adicional de la API')),
                ('alignment', models.JSONField(blank=True, default=dict, help_text='Datos de sincronización carácter por carácter')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, help_text='ID de la generación en ElevenLabs (si aplica)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='core.project')),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audios',
                'ordering': ['-created_at'],
            },
        ),
    ]
