# Generated by Django 5.1.6 on 2025-11-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_scene_audio_duration_scene_audio_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='visual_prompt',
            field=models.TextField(blank=True, help_text='Prompt visual para generar el video (Veo/Sora/Vuela) - en inglés', null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='script_text',
            field=models.TextField(help_text='Texto literal y completo del guión para narración (HeyGen + ElevenLabs)'),
        ),
    ]
