# Generated by Django 5.1.6 on 2025-11-06 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_scene_visual_prompt_alter_scene_script_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la pista musical', max_length=255)),
                ('prompt', models.TextField(help_text='Prompt usado para generar la música')),
                ('duration_ms', models.IntegerField(help_text='Duración de la música en milisegundos')),
                ('composition_plan', models.JSONField(blank=True, help_text='Plan de composición detallado (JSON) usado para generar la música', null=True)),
                ('song_metadata', models.JSONField(blank=True, help_text='Metadatos de la canción generada (tempo, key, mood, etc.)', null=True)),
                ('gcs_path', models.CharField(blank=True, help_text='Path en GCS donde está almacenada la música', max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('generating', 'Generando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('elevenlabs_track_id', models.CharField(blank=True, help_text='ID del track en ElevenLabs (si aplica)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se generó la música', null=True)),
                ('project', models.ForeignKey(help_text='Proyecto al que pertenece esta música', on_delete=django.db.models.deletion.CASCADE, related_name='music_tracks', to='core.project')),
            ],
            options={
                'verbose_name': 'Música',
                'verbose_name_plural': 'Músicas',
                'db_table': 'music',
                'ordering': ['-created_at'],
            },
        ),
    ]
