# Generated by Django 5.2.7 on 2025-11-19 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_music'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Usuario propietario del proyecto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('editor', 'Editor')], default='editor', help_text='Rol del usuario en el proyecto', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el usuario se unió al proyecto')),
                ('project', models.ForeignKey(help_text='Proyecto al que pertenece el miembro', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.project')),
                ('user', models.ForeignKey(help_text='Usuario miembro del proyecto', on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de Proyecto',
                'verbose_name_plural': 'Miembros de Proyectos',
                'ordering': ['-joined_at'],
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Usuarios con acceso al proyecto', related_name='shared_projects', through='core.ProjectMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email del usuario invitado', max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('editor', 'Editor')], default='editor', help_text='Rol que se asignará al usuario cuando acepte', max_length=20)),
                ('token', models.CharField(help_text='Token único para aceptar la invitación', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='pending', help_text='Estado de la invitación', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la invitación')),
                ('expires_at', models.DateTimeField(help_text='Fecha de expiración de la invitación')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='Fecha en que se aceptó la invitación', null=True)),
                ('invited_by', models.ForeignKey(help_text='Usuario que envió la invitación', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Proyecto al que se invita', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.project')),
            ],
            options={
                'verbose_name': 'Invitación de Proyecto',
                'verbose_name_plural': 'Invitaciones de Proyectos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='core_projec_token_16853f_idx'), models.Index(fields=['email', 'status'], name='core_projec_email_e947ff_idx')],
            },
        ),
    ]
