# Generated by Django 5.2.7 on 2025-11-19 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_assign_project_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='core.project'),
        ),
        migrations.AlterField(
            model_name='image',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project'),
        ),
        migrations.AlterField(
            model_name='music',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_tracks', to='core.project'),
        ),
        migrations.AlterField(
            model_name='script',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='core.project'),
        ),
        migrations.AlterField(
            model_name='video',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.project'),
        ),
    ]
