# Generated by Django 5.2.7 on 2025-11-19 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_audio_project_alter_image_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este audio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó esta imagen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='music',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó esta música', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='script',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este guión', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este video', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
