# Generated by Django 5.2.7 on 2025-11-24 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0017_audio_created_by_image_created_by_music_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.DecimalField(decimal_places=2, default=0, help_text='Saldo actual de créditos', max_digits=10)),
                ('total_purchased', models.DecimalField(decimal_places=2, default=0, help_text='Total de créditos comprados históricamente', max_digits=10)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, help_text='Total de créditos gastados históricamente', max_digits=10)),
                ('monthly_limit', models.IntegerField(default=1000, help_text='Límite mensual de créditos')),
                ('current_month_usage', models.DecimalField(decimal_places=2, default=0, help_text='Créditos usados en el mes actual', max_digits=10)),
                ('last_reset_date', models.DateField(blank=True, help_text='Última fecha de reset mensual', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Créditos de Usuario',
                'verbose_name_plural': 'Créditos de Usuarios',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Compra'), ('spend', 'Gasto'), ('refund', 'Reembolso'), ('adjustment', 'Ajuste'), ('monthly_reset', 'Reset Mensual')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cantidad de créditos (positivo para compras, negativo para gastos)', max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Saldo antes de la transacción', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Saldo después de la transacción', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Descripción de la transacción')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('service_name', models.CharField(blank=True, help_text='Nombre del servicio usado (gemini_veo, sora, etc.)', max_length=50)),
                ('metadata', models.JSONField(default=dict, help_text='Información adicional (duración, tokens, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción de Créditos',
                'verbose_name_plural': 'Transacciones de Créditos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_credit_user_id_c97634_idx'), models.Index(fields=['user', 'transaction_type'], name='core_credit_user_id_a1d033_idx'), models.Index(fields=['service_name', '-created_at'], name='core_credit_service_034c55_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('gemini_veo', 'Gemini Veo'), ('sora', 'OpenAI Sora'), ('heygen_avatar_v2', 'HeyGen Avatar V2'), ('heygen_avatar_iv', 'HeyGen Avatar IV'), ('vuela_ai', 'Vuela.ai'), ('gemini_image', 'Gemini Image'), ('elevenlabs', 'ElevenLabs TTS'), ('elevenlabs_music', 'ElevenLabs Music')], max_length=50)),
                ('operation_type', models.CharField(choices=[('video_generation', 'Generación de Video'), ('image_generation', 'Generación de Imagen'), ('audio_generation', 'Generación de Audio'), ('music_generation', 'Generación de Música'), ('preview_generation', 'Generación de Preview')], max_length=50)),
                ('tokens_used', models.IntegerField(blank=True, help_text='Tokens consumidos (si aplica)', null=True)),
                ('credits_spent', models.DecimalField(decimal_places=2, help_text='Créditos gastados', max_digits=10)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=4, help_text='Costo real en USD', max_digits=10, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Info adicional (duración, resolución, caracteres, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso de Servicio',
                'verbose_name_plural': 'Usos de Servicios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_servic_user_id_664517_idx'), models.Index(fields=['user', 'service_name'], name='core_servic_user_id_cee68c_idx'), models.Index(fields=['service_name', '-created_at'], name='core_servic_service_5278a0_idx'), models.Index(fields=['created_at'], name='core_servic_created_ec7d32_idx')],
            },
        ),
    ]
