# Generated by Django 5.2.7 on 2025-11-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_increase_video_type_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='ai_service',
            field=models.CharField(choices=[('gemini_veo', 'Gemini Veo'), ('sora', 'OpenAI Sora'), ('heygen_v2', 'HeyGen Avatar V2'), ('heygen_avatar_iv', 'HeyGen Avatar IV'), ('vuela_ai', 'Vuela.ai'), ('higgsfield_dop_standard', 'Higgsfield DoP Standard'), ('higgsfield_dop_preview', 'Higgsfield DoP Preview'), ('higgsfield_seedance_v1_pro', 'Higgsfield Seedance V1 Pro'), ('higgsfield_kling_v2_1_pro', 'Higgsfield Kling V2.1 Pro'), ('kling_v1', 'Kling V1'), ('kling_v1_5', 'Kling V1.5'), ('kling_v1_6', 'Kling V1.6'), ('kling_v2_master', 'Kling V2 Master'), ('kling_v2_1', 'Kling V2.1'), ('kling_v2_5_turbo', 'Kling V2.5 Turbo')], help_text='Servicio de IA seleccionado para generar el video', max_length=50),
        ),
    ]
