# Generated by Django 5.2.7 on 2025-12-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='generationtask',
            new_name='generation__user_id_7f7fbf_idx',
            old_name='core_genera_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='generationtask',
            new_name='generation__task_ty_5520e3_idx',
            old_name='core_genera_task_ty_idx',
        ),
        migrations.RenameIndex(
            model_name='generationtask',
            new_name='generation__status_9aa419_idx',
            old_name='core_genera_status_idx',
        ),
        migrations.RenameIndex(
            model_name='generationtask',
            new_name='generation__queue_n_5acd90_idx',
            old_name='core_genera_queue_n_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_92ac92_idx',
            old_name='core_notifi_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_6dfb7b_idx',
            old_name='core_notifi_user_ty_idx',
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('heygen_avatar_v2', 'HeyGen Avatar V2'), ('heygen_avatar_iv', 'HeyGen Avatar IV'), ('gemini_veo', 'Gemini Veo'), ('sora', 'OpenAI Sora'), ('higgsfield_dop_standard', 'Higgsfield DoP Standard'), ('higgsfield_dop_preview', 'Higgsfield DoP Preview'), ('higgsfield_seedance_v1_pro', 'Higgsfield Seedance V1 Pro'), ('higgsfield_kling_v2_1_pro', 'Higgsfield Kling V2.1 Pro'), ('kling_v1', 'Kling V1'), ('kling_v1_5', 'Kling V1.5'), ('kling_v1_6', 'Kling V1.6'), ('kling_v2_master', 'Kling V2 Master'), ('kling_v2_1', 'Kling V2.1'), ('kling_v2_5_turbo', 'Kling V2.5 Turbo'), ('manim_quote', 'Manim Quote')], max_length=30),
        ),
    ]
