# Generated by Django 5.2.7 on 2025-12-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_core_genera_user_id_idx_generation__user_id_7f7fbf_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationtask',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Celery task ID', max_length=255, null=True, unique=True),
        ),
    ]
