# Generated by Django 5.2.7 on 2025-12-01 16:23

import uuid
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    for project in Project.objects.all():
        project.uuid = uuid.uuid4()
        project.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_uuid_to_video_image_audio'),
    ]

    operations = [
        # Paso 1: Agregar campo sin unique
        migrations.AddField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        # Paso 2: Generar UUIDs para registros existentes
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        # Paso 3: Hacer el campo unique (quitar null)
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
