# Generated by Django 5.2.7 on 2025-12-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_uuid_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='composition_plan',
            field=models.JSONField(blank=True, help_text='Plan de composición detallado (JSON)', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='duration_ms',
            field=models.IntegerField(blank=True, help_text='Duración de la música en milisegundos', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='elevenlabs_track_id',
            field=models.CharField(blank=True, help_text='ID del track en ElevenLabs Music', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='prompt',
            field=models.TextField(blank=True, help_text='Prompt usado para generar la música', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='song_metadata',
            field=models.JSONField(blank=True, help_text='Metadatos de la canción (tempo, key, mood, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='type',
            field=models.CharField(choices=[('tts', 'Text-to-Speech'), ('music', 'Música Generada')], db_index=True, default='tts', help_text='Tipo de audio: TTS o música generada', max_length=20),
        ),
        migrations.AlterField(
            model_name='audio',
            name='text',
            field=models.TextField(blank=True, help_text='Texto para convertir a voz (TTS)', null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='voice_id',
            field=models.CharField(blank=True, help_text='ID de la voz en ElevenLabs (TTS)', max_length=100, null=True),
        ),
    ]
