# Generated by Django 5.2.7 on 2025-12-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_unify_audio_music'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
