# Generated by Django 5.2.7 on 2025-12-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_unify_audio_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationtask',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Celery task ID (puede ser null antes de que Celery procese la tarea)', max_length=255, null=True),
        ),
    ]
