# Generated by Django 5.2.7 on 2025-12-02 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_squashed_0030_remove_unique_from_task_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID único de la plantilla', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de la plantilla (ej: "Raven Transition")', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de la plantilla')),
                ('template_type', models.CharField(choices=[('video', 'Video'), ('image', 'Imagen'), ('agent', 'Agente')], db_index=True, default='video', help_text='Tipo de contenido que genera', max_length=20)),
                ('prompt_text', models.TextField(help_text='Texto del prompt que se enviará al servicio de IA (máximo 800 caracteres)', max_length=800)),
                ('recommended_service', models.CharField(blank=True, choices=[('sora', 'Sora'), ('higgsfield', 'Higgsfield'), ('gemini_veo', 'Gemini Veo'), ('agent', 'Agente')], db_index=True, help_text='Servicio recomendado para usar este template', max_length=50, null=True)),
                ('preview_url', models.URLField(blank=True, help_text='URL del video/imagen de ejemplo', max_length=500, null=True)),
                ('is_public', models.BooleanField(db_index=True, default=False, help_text='Si la plantilla es visible para todos los usuarios')),
                ('upvotes', models.PositiveIntegerField(default=0, help_text='Número de votos positivos')),
                ('downvotes', models.PositiveIntegerField(default=0, help_text='Número de votos negativos')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Número de veces que se ha usado')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si la plantilla está activa y disponible')),
                ('created_by', models.ForeignKey(help_text='Usuario que creó la plantilla', on_delete=django.db.models.deletion.CASCADE, related_name='created_prompt_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Prompt',
                'verbose_name_plural': 'Plantillas de Prompts',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPromptFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se marcó como favorito')),
                ('template', models.ForeignKey(help_text='Template favorito', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.prompttemplate')),
                ('user', models.ForeignKey(help_text='Usuario que marca como favorito', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template Favorito',
                'verbose_name_plural': 'Templates Favoritos',
            },
        ),
        migrations.CreateModel(
            name='UserPromptVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], help_text='Tipo de voto', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha del voto')),
                ('template', models.ForeignKey(help_text='Template votado', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.prompttemplate')),
                ('user', models.ForeignKey(help_text='Usuario que vota', on_delete=django.db.models.deletion.CASCADE, related_name='prompt_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto de Template',
                'verbose_name_plural': 'Votos de Templates',
            },
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['template_type', 'is_public', 'is_active'], name='core_prompt_templat_7d250f_idx'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['recommended_service', 'is_public', 'is_active'], name='core_prompt_recomme_319c20_idx'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['created_by', 'is_active'], name='core_prompt_created_9c5569_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prompttemplate',
            unique_together={('name', 'created_by')},
        ),
        migrations.AddIndex(
            model_name='userpromptfavorite',
            index=models.Index(fields=['user', 'created_at'], name='core_userpr_user_id_a2e472_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpromptfavorite',
            unique_together={('user', 'template')},
        ),
        migrations.AddIndex(
            model_name='userpromptvote',
            index=models.Index(fields=['template', 'vote_type'], name='core_userpr_templat_ecce26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpromptvote',
            unique_together={('user', 'template')},
        ),
    ]
