# Generated by Django 5.2.7 on 2025-12-02 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_prompt_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó la plantilla (None para templates del sistema)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_prompt_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
