# Generated by Django 5.2.7 on 2025-12-02 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_make_created_by_nullable_in_prompt_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prompttemplate',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', False)), fields=('name', 'created_by'), name='unique_template_per_user'),
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', True)), fields=('name', 'template_type'), name='unique_system_template'),
        ),
    ]
