# Generated by Django 5.2.7 on 2025-12-02 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_update_prompt_template_unique_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prompttemplate',
            name='unique_system_template',
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', True)), fields=('name', 'template_type', 'recommended_service'), name='unique_system_template'),
        ),
    ]
