# Generated by Django 5.2.7 on 2025-12-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_fix_prompt_template_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='prompt_text',
            field=models.TextField(help_text='Texto del prompt que se enviará al servicio de IA (máximo 1200 caracteres)', max_length=1200),
        ),
    ]
