# Generated by Django 5.2.7 on 2025-12-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_increase_prompt_text_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='prompt_text',
            field=models.TextField(help_text='Texto del prompt que se enviará al servicio de IA (máximo 2000 caracteres)', max_length=2000),
        ),
    ]
