# Generated by Django 5.2.7 on 2025-12-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_video_format_to_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='desired_duration_min',
            field=models.FloatField(default=5, help_text='Duración deseada del video en minutos (puede ser decimal, ej: 1.5 para 1 min 30 seg)'),
        ),
        migrations.AlterField(
            model_name='script',
            name='video_type',
            field=models.CharField(blank=True, choices=[('ultra', 'Modo Ultra (Veo3 y Sora2)'), ('avatar', 'Con Avatares (HeyGen)'), ('general', 'Video General')], help_text='Tipo de video para el flujo del agente (qué servicios usar)', max_length=20, null=True),
        ),
    ]
