# Generated by Django 5.2.7 on 2025-12-04 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_change_desired_duration_to_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece (para consultas directas)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='core.project'),
        ),
    ]
