# Generated by Django 5.2.7 on 2025-12-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_allow_null_project_in_scene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='type',
            field=models.CharField(choices=[('tts', 'Text-to-Speech'), ('music', 'Música Generada'), ('uploaded_audio', 'Audio Subido')], db_index=True, default='tts', help_text='Tipo de audio: TTS o música generada', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('uploaded_image', 'Imagen Subida'), ('text_to_image', 'Texto a Imagen'), ('image_to_image', 'Imagen a Imagen (Edición)'), ('multi_image', 'Múltiples Imágenes (Composición)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('uploaded_video', 'Video Subido'), ('heygen_avatar_v2', 'HeyGen Avatar V2'), ('heygen_avatar_iv', 'HeyGen Avatar IV'), ('gemini_veo', 'Gemini Veo'), ('sora', 'OpenAI Sora'), ('higgsfield_dop_standard', 'Higgsfield DoP Standard'), ('higgsfield_dop_preview', 'Higgsfield DoP Preview'), ('higgsfield_seedance_v1_pro', 'Higgsfield Seedance V1 Pro'), ('higgsfield_kling_v2_1_pro', 'Higgsfield Kling V2.1 Pro'), ('kling_v1', 'Kling V1'), ('kling_v1_5', 'Kling V1.5'), ('kling_v1_6', 'Kling V1.6'), ('kling_v2_master', 'Kling V2 Master'), ('kling_v2_1', 'Kling V2.1'), ('kling_v2_5_turbo', 'Kling V2.5 Turbo'), ('manim_quote', 'Manim Quote')], max_length=30),
        ),
    ]
