"""
Django settings for atenea project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# Global app-use permission (set to a permission string like 'core.use_app' to enforce)
# If None, middleware will not enforce a global "use the app" permission.
REQUIRED_APP_PERMISSION = None

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En desarrollo: lee de .env
# En CI: lee de GitHub Secrets (SECRET_KEY_CI)
# En producción: lee de variables de entorno del servidor
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS: dominios permitidos para la aplicación
# Se puede configurar via variable de entorno o usar los conocidos
allowed_hosts_env = config('ALLOWED_HOSTS', default='')

# Dominios de producción conocidos (siempre incluidos)
production_hosts = [
    'dev.atenea.nxhumans.com',
    'demo.atenea.nxhumans.com',
    'atenea.nxhumans.com',
    'dev.atenea.ailumtech.com',
    'demo.atenea.ailumtech.com',
    'test.atenea.ailumtech.com',
    'npm.atenea.ailumtech.com',
]

if allowed_hosts_env:
    # Si hay variable de entorno, usar esos valores y añadir los de producción
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()]
    # Añadir dominios de producción conocidos (sin duplicados)
    for host in production_hosts:
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)
else:
    # Dominios por defecto (desarrollo)
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    # Añadir dominios de producción conocidos
    ALLOWED_HOSTS.extend(production_hosts)

# CSRF Trusted Origins
# Añadir los dominios desde los que se pueden hacer peticiones POST
# Por defecto incluye localhost para desarrollo
default_csrf_origins = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Añadir dominios de producción desde variable de entorno o usar los conocidos
csrf_origins_env = config('CSRF_TRUSTED_ORIGINS', default='')
if csrf_origins_env:
    CSRF_TRUSTED_ORIGINS = csrf_origins_env.split(',')
else:
    # Si no hay variable de entorno, usar los dominios conocidos
    CSRF_TRUSTED_ORIGINS = default_csrf_origins.copy()
    # Añadir dominios de producción conocidos (nxhumans)
    production_domains = [
        'https://dev.atenea.nxhumans.com',
        'https://demo.atenea.nxhumans.com',
        'https://atenea.nxhumans.com',
    ]
    CSRF_TRUSTED_ORIGINS.extend(production_domains)
    # Añadir dominios de producción conocidos (ailumtech)
    production_domains_ailumtech = [
        'https://dev.atenea.ailumtech.com',
        'https://demo.atenea.ailumtech.com',
        'https://test.atenea.ailumtech.com',
        'https://npm.atenea.ailumtech.com',
    ]
    CSRF_TRUSTED_ORIGINS.extend(production_domains_ailumtech)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party
    # 'whitenoise',  # Para servir archivos estáticos (comentado temporalmente)
    'tailwind',
    'theme',  # App de Tailwind
    'django_celery_beat',  # Celery Beat para tareas periódicas
    'django_celery_results',  # Celery Results para almacenar resultados
    'channels',  # Django Channels para WebSockets
    
    # Local apps
    'core',
]

# Solo en desarrollo
if DEBUG:
    INSTALLED_APPS.append('django_browser_reload')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',  # Para servir archivos estáticos (comentado temporalmente)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.LoginRequiredMiddleware', # Middleware personalizado de login
]

# Solo en desarrollo
if DEBUG:
    MIDDLEWARE.append('django_browser_reload.middleware.BrowserReloadMiddleware')

ROOT_URLCONF = 'atenea.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'atenea.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration
# Use SQLite for development/CI, PostgreSQL for production
if config('USE_SQLITE', default=True, cast=bool):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Usar DATABASE_URL si está disponible
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(
            config('DATABASE_URL', default=''),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Google Cloud Storage Configuration
GCS_BUCKET_NAME = config('GCS_BUCKET_NAME', default='devid-bucket-0001')
GCS_PROJECT_ID = config('GCS_PROJECT_ID', default='proeduca-472312')
GOOGLE_APPLICATION_CREDENTIALS = config(
    'GOOGLE_APPLICATION_CREDENTIALS',
    default=str(BASE_DIR / 'credentials.json')
)

# Set the credentials path as environment variable for Google Cloud SDK
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = GOOGLE_APPLICATION_CREDENTIALS

# API Keys Configuration
HEYGEN_API_KEY = config('HEYGEN_API_KEY', default='')
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
OPENAI_API_KEY = config('OPENAI_API_KEY', default='')
FREEPIK_API_KEY = config('FREEPIK_API_KEY', default='')
VUELA_AI_API_KEY = config('VUELA_AI_API_KEY', default='')
ELEVENLABS_API_KEY = config('ELEVENLABS_API_KEY', default='')
# Higgsfield
HIGGSFIELD_API_KEY_ID = config('HIGGSFIELD_API_KEY_ID', default='')
HIGGSFIELD_API_KEY = config('HIGGSFIELD_API_KEY', default='')
# Kling
KLING_ACCESS_KEY = config('KLING_ACCESS_KEY', default='')
KLING_SECRET_KEY = config('KLING_SECRET_KEY', default='')

# Stock Content APIs
PEXELS_API_KEY = config('PEXELS_API_KEY', default='')
UNSPLASH_ACCESS_KEY = config('UNSPLASH_ACCESS_KEY', default='')  # Access Key (Client-ID) de Unsplash
PIXABAY_API_KEY = config('PIXABAY_API_KEY', default='')
FREESOUND_API_KEY = config('FREESOUND_API_KEY', default='')  # Token de acceso de FreeSound (para búsquedas)
# FREESOUND_CLIENT_ID y FREESOUND_CLIENT_SECRET solo se necesitan para OAuth2 (descargas, no implementado aún)

# ElevenLabs Defaults
ELEVENLABS_DEFAULT_MODEL = config('ELEVENLABS_DEFAULT_MODEL', default='eleven_turbo_v2_5')
ELEVENLABS_DEFAULT_VOICE_ID = config('ELEVENLABS_DEFAULT_VOICE_ID', default='pFZP5JQG7iQjIQuC4Bku')
ELEVENLABS_DEFAULT_VOICE_NAME = config('ELEVENLABS_DEFAULT_VOICE_NAME', default='Aria')
ELEVENLABS_DEFAULT_LANGUAGE = config('ELEVENLABS_DEFAULT_LANGUAGE', default='es')
ELEVENLABS_DEFAULT_STABILITY = config('ELEVENLABS_DEFAULT_STABILITY', default=0.5, cast=float)
ELEVENLABS_DEFAULT_SIMILARITY_BOOST = config('ELEVENLABS_DEFAULT_SIMILARITY_BOOST', default=0.75, cast=float)
ELEVENLABS_DEFAULT_STYLE = config('ELEVENLABS_DEFAULT_STYLE', default=0.0, cast=float)
ELEVENLABS_DEFAULT_SPEED = config('ELEVENLABS_DEFAULT_SPEED', default=1.0, cast=float)

# HeyGen Defaults
# Avatar por defecto: Abigail (Upper Body)
HEYGEN_DEFAULT_AVATAR_ID = config('HEYGEN_DEFAULT_AVATAR_ID', default='Abigail_expressive_2024112501')
# Voz por defecto: Mujer, español de España
HEYGEN_DEFAULT_VOICE_ID = config('HEYGEN_DEFAULT_VOICE_ID', default='42a4920ccdba473c8df2b2c9b0a192d5')

# Redis Configuration
REDIS_URL = config('REDIS_URL', default='redis://redis-13128.c12.us-east-1-4.ec2.redns.redis-cloud.com:13128')
REDIS_PASSWORD = config('REDIS_PASSWORD', default='')

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'core': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Tailwind Configuration
TAILWIND_APP_NAME = 'theme'

# Para desarrollo local
INTERNAL_IPS = [
    "127.0.0.1",
]

# ====================================
# LANGCHAIN & AGENT CONFIGURATION
# ====================================

# LangSmith Configuration (Observabilidad)
LANGSMITH_API_KEY = config('LANGSMITH_API_KEY', default='')
LANGSMITH_PROJECT = config('LANGSMITH_PROJECT', default='atenea-script-agent')

# LLM Provider Configuration
DEFAULT_LLM_PROVIDER = config('DEFAULT_LLM_PROVIDER', default='openai')  # 'openai' or 'gemini'
DEFAULT_LLM_MODEL = config('DEFAULT_LLM_MODEL', default=None)  # None = use default for provider
LLM_TEMPERATURE = config('LLM_TEMPERATURE', default=0.7, cast=float)
LLM_MAX_RETRIES = config('LLM_MAX_RETRIES', default=2, cast=int)

# Agent Cache Configuration
AGENT_CACHE_TTL = config('AGENT_CACHE_TTL', default=86400, cast=int)  # 24 horas en segundos
AGENT_CACHE_ENABLED = config('AGENT_CACHE_ENABLED', default=True, cast=bool)

# Stock Search Cache Configuration
# Manejar caso donde STOCK_CACHE_TTL está vacío en .env
try:
    stock_cache_ttl_str = config('STOCK_CACHE_TTL', default='3600')
    STOCK_CACHE_TTL = int(stock_cache_ttl_str) if stock_cache_ttl_str else 3600
except (ValueError, TypeError):
    STOCK_CACHE_TTL = 3600  # 1 hora en segundos

# Feature Flag: Usar LangChain en lugar de n8n
USE_LANGCHAIN_AGENT = config('USE_LANGCHAIN_AGENT', default=False, cast=bool)

# Rate Limiting (para implementar después)
AGENT_RATE_LIMIT_PER_USER = config('AGENT_RATE_LIMIT_PER_USER', default=10, cast=int)  # requests/hora
AGENT_RATE_LIMIT_PER_PROJECT = config('AGENT_RATE_LIMIT_PER_PROJECT', default=5, cast=int)  # requests/hora

# ====================================
# RAG ASSISTANT CONFIGURATION
# ====================================

# RAG Assistant
RAG_ENABLED = config('RAG_ENABLED', default=True, cast=bool)
RAG_DOCS_PATH = config('RAG_DOCS_PATH', default='docs/api')  # Path relativo a BASE_DIR (solo docs/api)
RAG_EMBEDDING_PROVIDER = config('RAG_EMBEDDING_PROVIDER', default='openai')  # 'openai' o 'google'
RAG_EMBEDDING_MODEL = config('RAG_EMBEDDING_MODEL', default='text-embedding-3-small')
RAG_LLM_PROVIDER = config('RAG_LLM_PROVIDER', default=None)  # None = usar DEFAULT_LLM_PROVIDER
RAG_LLM_MODEL = config('RAG_LLM_MODEL', default=None)  # None = usar default del provider
RAG_TOP_K = config('RAG_TOP_K', default=5, cast=int)  # Documentos a recuperar
RAG_CHUNK_SIZE = config('RAG_CHUNK_SIZE', default=1000, cast=int)
RAG_CHUNK_OVERLAP = config('RAG_CHUNK_OVERLAP', default=200, cast=int)
RAG_VECTOR_STORE_PATH = config('RAG_VECTOR_STORE_PATH', default='.rag_store')  # Carpeta para guardar índices
RAG_PROJECT_NAME = config('RAG_PROJECT_NAME', default='atenea-doc-assistant')  # Para LangSmith
AGENT_RATE_LIMIT_GLOBAL = config('AGENT_RATE_LIMIT_GLOBAL', default=100, cast=int)  # requests/hora

# ====================================
# CELERY CONFIGURATION
# ====================================

# Detectar automáticamente si estamos en Docker o desarrollo local
# Intentamos resolver el hostname 'redis' (servicio Docker)
# Si falla, usamos 'localhost' (desarrollo local)
def get_redis_host():
    """Detecta automáticamente el host de Redis según el entorno"""
    import socket
    try:
        # Intentar resolver 'redis' (servicio Docker)
        socket.gethostbyname('redis')
        return 'redis'
    except (socket.gaierror, OSError):
        # Si falla, estamos en desarrollo local
        return 'localhost'

# Celery Configuration
# En Docker, usar el nombre del servicio: redis://redis:6379/0
# En desarrollo local, usar: redis://localhost:6379/0
_redis_host = get_redis_host()
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default=f'redis://{_redis_host}:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default=f'redis://{_redis_host}:6379/0')

# Serialización
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Tracking
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutos máximo
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutos soft limit

# Task Routes (routing por cola)
CELERY_TASK_ROUTES = {
    'core.tasks.generate_video_task': {'queue': 'video_generation'},
    'core.tasks.generate_image_task': {'queue': 'image_generation'},
    'core.tasks.generate_audio_task': {'queue': 'audio_generation'},
    'core.tasks.generate_scene_preview_task': {'queue': 'scene_processing'},
    'core.tasks.combine_video_audio_task': {'queue': 'scene_processing'},
    'core.tasks.poll_video_status_task': {'queue': 'default'},
    'core.tasks.poll_image_status_task': {'queue': 'default'},
    'core.tasks.poll_audio_status_task': {'queue': 'default'},
    'core.tasks.remove_image_background_task': {'queue': 'image_generation'},
}

# Prioridades por tipo (dentro de cada cola)
# Mayor número = mayor prioridad (1-10)
CELERY_TASK_DEFAULT_PRIORITY = 5
CELERY_TASK_PRIORITY_MAP = {
    'core.tasks.generate_scene_preview_task': 10,  # Previews alta prioridad
    'core.tasks.generate_video_task': 5,  # Videos normal
    'core.tasks.generate_image_task': 5,  # Imágenes normal
    'core.tasks.generate_audio_task': 5,  # Audios normal
}

# Retry Configuration
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Pool Configuration: Condicional por SO
# Windows: threading pool (multiprocessing tiene issues con billiard)
# Linux/Mac: prefork pool (multiprocessing, mejor performance)
import platform
CURRENT_OS = platform.system()
if CURRENT_OS == 'Windows':
    # Windows: usa threading para evitar problemas de billiard con semáforos
    CELERY_WORKER_POOL = 'threads'
    CELERY_WORKER_MAX_TASKS_PER_CHILD = None
    CELERY_WORKER_CONCURRENCY = 4  # Threads: más conservador
else:
    # Linux/Mac: usa prefork (multiprocessing) para mejor performance
    CELERY_WORKER_POOL = 'prefork'
    CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000  # Reciclaje de procesos cada 1000 tasks
    CELERY_WORKER_CONCURRENCY = 4  # Procesos

# Celery Beat Schedule (tareas periódicas)
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # Limpieza de notificaciones antiguas (diaria a las 2 AM)
    'cleanup-old-notifications': {
        'task': 'core.tasks.cleanup_old_notifications',
        'schedule': crontab(hour=2, minute=0),
    },
    
    # Verificar tareas atascadas (cada hora)
    'check-stuck-tasks': {
        'task': 'core.tasks.check_stuck_tasks',
        'schedule': crontab(minute=0),
    },
}

# ====================================
# CHANNELS CONFIGURATION (WebSockets)
# ====================================

ASGI_APPLICATION = 'atenea.asgi.application'

# CHANNEL_LAYERS Configuration
# Para desarrollo local, usar localhost. Para producción/Docker, usar CHANNEL_REDIS_URL o REDIS_URL.
# En Docker, usar el nombre del servicio: redis://redis:6379/1
channel_redis_url = config('CHANNEL_REDIS_URL', default=f'redis://{_redis_host}:6379/1')

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            # channels-redis requiere URLs string, no tuplas
            "hosts": [channel_redis_url],
        },
    },
}

